config/routes.rb
RedditClone::Application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :links, only: [:edit, :update, :destroy, :new, :create, :show] do
    resources :votes, only: [:create]
  end
  resources :comments, only: [:new, :create, :edit, :update] # new?

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :link_id, :parent_comment_id, :user_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @link_id = params[:link_id]
    @parent_comment_id = params[:parent_comment_id]
    render :new
  end

  def create
    comment = Comment.new(params[:comment])

    if comment.save
      redirect_to link_url(comment.link_id)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] += comment.errors.full_messages
      render :new
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token"
        value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[link_id]" value="<%= @link_id %>">

  <input type="hidden" name="comment[parent_comment_id]"
        value="<%= @parent_comment_id %>">

  <br>
  <label>
    Comment
    <textarea name="comment[body]"></textarea>
  </label>
  <br>

  <input type="submit" value="Post comment">
</form>