config/routes.rb
RedditClone::Application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :links, only: [:edit, :update, :destroy, :new, :create, :show] do
    resources :votes, only: [:create]
  end
  resources :comments, only: [:new, :create, :edit, :update] # new?

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :moderator, :name

  validates :moderator, presence: true
  validates :name, presence: true

  belongs_to :user, class_name: "User", primary_key: :id, foreign_key: :moderator

  has_many :link_subs, class_name: "LinkSub", primary_key: :id, foreign_key: :sub_id

  has_many :links, through: :link_subs, source: :link, inverse_of: :subs


end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  include SubsHelper

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    @links = @sub.links.sort_by { |link| link.score }.reverse
    render :show
  end

  def new
    @url = subs_url
    @sub = Sub.new

    render :new
  end

  def create
    #begin
      @sub = Sub.new(params[:sub])
      @links = links_from_params(params)
      #fail

      @have_errors = false
      ActiveRecord::Base.transaction do
        # save here
        @sub.save

        @links.each do |link|
          # if this were done using a hidden field in the form, all links would
          # be nonnil
          link.user_id = current_user.id
          link.subs ||= []
          link.subs << @sub
          link.save
        end
        #raise SpecialError #unless @sub.valid? && @links.all? { |link| link.valid? }
        @sub.links ||= []
        @sub.links += @links
        @sub.save
        @have_errors = true unless @sub.valid? && @links.all? { |link| link.valid? }
      end


    #rescue SpecialError
    if @have_errors
      link_errors = @links.map do |link|
        link.errors.full_messages
      end

      link_errors = link_errors.flatten
      flash.now[:errors] ||= []
      flash.now[:errors] = @sub.errors.full_messages + link_errors
      #fail
      render :new
    else
      redirect_to sub_url(@sub)
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    redirect_to :show unless current_user == @sub.moderator
    @url = sub_url(@sub)

    render :edit
  end

  def update

  end
end

class SpecialError < StandardError

end

app/helpers/subs_helper.rb
module SubsHelper

  def links_from_params(parameters)
    links = []

    parameters[:links].each do |key, value|
      value.each do |key2, value2|
        if value2 && value2 != ""
          links << Link.new(value)
          break
        end
      end
    end

    links
  end
end

app/views/subs/_sub_form.html.erb
<form action="<%= url %>" method="post">

  <input type="hidden" name="authenticity_token"
          value="<%= form_authenticity_token %>">

  <input type="hidden" name="sub[moderator]" value="<%= current_user.id %>">

  <label>
    Name of sub
    <input type="text" name="sub[name]" value="<%= sub.name %>">
  </label>
  <br>

  <h3>Add Links</h3>
  <% unless sub.persisted? %>
    <!-- Make a helper for this? -->
    <% 5.times do |i| %>
    <br>

    Link <%= (i + 1).to_s %>
    <br>

    <label>
      Link name
      <input type="text" name="links[<%= i.to_s %>][title]"
        value="<%#= sub.link[i].title unless sub.nil? || sub.link[i].nil? %>">
    </label>
    <br>

    <label>
      Link URL
      <input type="text" name="links[<%= i.to_s %>][url]"
          value="<%#= sub.link[i].url unless sub.nil? || sub.link[i].nil? %>">
    </label>
    <br>

    <label>
      Link text
      <textarea name="links[<%= i.to_s %>][body]"><%#= sub.link[i].body unless sub.nil? || sub.link[i].nil? %></textarea>
    </label>
    <br>

    <% end %>
  <% end %>

  <input type="submit" value="Create Sub">
</form>

<% flash.now[:errors].try(:each) do |error| %>
  <%= error.full_message %>
<% end %>

app/views/subs/edit.html.erb
<%= render "sub_form", url: @url, sub: @sub %>

app/views/subs/index.html.erb
<% @subs.each do |sub| %>
  <%= link_to sub.name, sub_url(sub) %>
<% end %>

app/views/subs/new.html.erb
<%= render "sub_form", url: @url, sub: @sub %>

app/views/subs/show.html.erb
<h3><%= @sub.name %></h3>

<ul>
  <% @links.each do |link| %>
  <li>
    <%= link.score %>
    <%= link_to link.title, link.url %>
    <%= link.body %>
    <%= link_to "Comments", link_url(link) %>
    <% if current_user && link.user_id == current_user.id %>
      <%= link_to "Edit this link", edit_link_url(link) %>
      <%= button_to "Delete this link", link_url(link), method: :delete %>
    <% end %>
    <%= button_to("Upvote", link_votes_url(link, user_vote: { vote: 1, user_id: current_user.id, link_id: link.id }), method: :post) %>
    <%= button_to("Downvote", link_votes_url(link, user_vote: { vote: -1, user_id: current_user.id, link_id: link.id }), method: :post) %>
  </li>
  <% end %>
</ul>